### ISSUE TITLE
provider/elastictranscoder: thumbnail creation

### ISSUE THREAD

**Issue by doncollins** [video-dev/video-transcoding-api#188]
When I create an Elastic Transcoder job, no thumbnails are generated. I'm not sure if this is working as intended, since there's no mention of thumbnails in the documentation, but I do see that `provider/elastictranscoder/aws.go` includes some hardcoded settings related to thumbnail generation when creating a preset.

It looks like the reason they're not being generated is that the `ThumbnailPattern` property of the `elastictranscoder.CreateJobOutput` objects is not being set anywhere.

**Comment by fsouza** [comment]
Hey @doncollins, thanks for opening this issue and sorry for the delayed response.

The transcoding-api doesn't support thumbnail presets at the moment, there are some hard coded values in the elastictranscoder provider because the parameters are required by the AWS ElasticTranscoder API.
