### ISSUE TITLE
V2 Release Status

### ISSUE THREAD

**Issue by adamthesax** [video-dev/video-transcoding-api#290]
Hi-

We are currently running v1.7.0 in production and are looking to plumb in some more options into the presets (b-frame, 2 pass encoding, etc). Before we get into writing any code the question is what is the current status of the v2 release?

It looks like bulk of the changes are changing the package name as a result of moving the repo from NYTimes to video-dev. Is `master` at a place where we can cut a release so we can get our current production deployment up to date and start working on new features?

Thanks!

**Comment by fsouza** [comment]
Hey @adamthesax, I believe so yeah. It was probably an oversight that we didn't cut a v2 release. Let me try to get something out tomorrow or Wednesday (just need to review what's going on with docker hub in CI).

**Comment by adamthesax** [comment]
Awesome thanks @fsouza!

**Comment by fsouza** [comment]
The Docker Hub thing required a credential update. v2.0.0 is out! 🎉

**Comment by adamthesax** [comment]
Fantastic! Thanks for the quick turn around. We'll get this deployed to our environment soon and start kicking the tires on this release. Then you'll hear from me again once we start getting into expanding some preset options.
